server {
    listen 80;
    server_name _;

    location /.well-known/matrix/client {
        default_type application/json;
        add_header Access-Control-Allow-Origin *;
        alias /usr/share/nginx/html/client.json;
    }

    location /.well-known/matrix/server {
        default_type application/json;
        alias /usr/share/nginx/html/server.json;
    }

    location / {
        return 404;
    }
}
